- replace: dest=/etc/sysconfig/docker regexp="#.INSECURE_REGISTRY='--insecure-registry'" replace=INSECURE_REGISTRY="'--insecure-registry fabric8-registry.usersys.redhat.com:5000 --insecure-registry docker-registry.{{ fabric8_domain }}:80'"
- name: restart docker
  service: name=docker state=restarted
