# install steps taken from https://access.redhat.com/articles/1519093
- hosts: all
  sudo: yes
  tasks:
    - include_vars: config.yml
    - name: "Register"
      redhat_subscription: state=present username={{ rhn_username }} password={{ rhn_password }} autosubscribe=true
    - name: "Manually attach to pool id as ansible support not working"
      shell: subscription-manager attach --pool={{ rhn_pool_id }}
    - name: "Enable repositories"
      shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-optional-rpms" --enable="rhel-7-server-rh-common-rpms"
    - name: "Install dependencies"
      yum: pkg={{item}} state=installed
      with_items:
        - wget
      yum: pkg={{item}} state=started
      with_items:
        - docker
    - name: Get add-user-from-github.sh script
      copy: src=add-user-from-github.sh dest=/root/add-user-from-github.sh owner=root group=root mode=777
    - name: Get add-user-from-github.sh script
      copy: src=add-fabric8-team.sh dest=/root/add-fabric8-team.sh owner=root group=root mode=777
    - name: Add fabric8 team public ssh keys
      shell: /root/add-fabric8-team.sh
    - lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
    - name: get red hat internal ddns client
      shell: curl -O http://hdn.corp.redhat.com/rhel7-csb-stage/RPMS/noarch/redhat-internal-ddns-client-1.3-7.el7.csb.noarch.rpm
    - name: Install client
      shell: rpm -ivh redhat-internal-ddns-client-1.3-7.el7.csb.noarch.rpm
    - shell: mkdir /etc/redhat-internal-ddns; touch /etc/redhat-internal-ddns/hosts
    - lineinfile: dest=/etc/redhat-internal-ddns/hosts state=present line='fabric8-registry usersys.redhat.com {{rhn_dns_hash}}'
    - shell: /usr/bin/redhat-internal-ddns-client.sh enable
    - shell: /usr/bin/redhat-internal-ddns-client.sh update
    - lineinfile: dest=/etc/sysconfig/network state=present line='HOSTNAME=fabric8-registry.usersys.redhat.com'
    - hostname: name=fabric8-registry.usersys.redhat.com
    - replace: dest=/etc/sysconfig/docker regexp="#.INSECURE_REGISTRY='--insecure-registry'" replace=INSECURE_REGISTRY="'--insecure-registry fabric8-registry.usersys.redhat.com:5000 --insecure-registry ce-registry.usersys.redhat.com'"
    - name: restart docker
      service: name=docker state=restarted
    - name: start private docker registry and registry UI service
      copy: src=./docker-registry.service dest=/etc/systemd/system/multi-user.target.wants/docker-registry.service owner=root group=root mode=0644
      copy: src=./docker-registry-ui.service dest=/etc/systemd/system/multi-user.target.wants/docker-registry-ui.service owner=root group=root mode=0644
      service: name=docker-registry state=started
      service: name=docker-registry-ui state=started
